"""Add threat_type to logs table

Revision ID: 3d5d91403fdb
Revises: 
Create Date: 2025-06-10 16:42:24.258297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d5d91403fdb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.add_column('alerts', sa.Column('threat_type', sa.String(length=100), nullable=False))
    op.add_column('alerts', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('alerts', sa.Column('confidence_score', sa.String(length=10), nullable=True))
    op.add_column('alerts', sa.Column('matched_patterns', sa.Text(), nullable=True))
    op.add_column('alerts', sa.Column('source_ip', sa.String(length=45), nullable=True))
    op.add_column('alerts', sa.Column('source_type', sa.String(length=50), nullable=True))
    op.add_column('alerts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('assigned_to', sa.String(length=100), nullable=True))
    op.add_column('alerts', sa.Column('resolution_notes', sa.Text(), nullable=True))
    op.alter_column('alerts', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alerts', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_source_ip'), 'alerts', ['source_ip'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_threat_type'), 'alerts', ['threat_type'], unique=False)
    op.drop_column('alerts', 'timestamp')
    op.add_column('logs', sa.Column('threat_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'threat_type')
    op.add_column('alerts', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_alerts_threat_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_source_ip'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.alter_column('alerts', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alerts', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('alerts', 'resolution_notes')
    op.drop_column('alerts', 'assigned_to')
    op.drop_column('alerts', 'updated_at')
    op.drop_column('alerts', 'created_at')
    op.drop_column('alerts', 'source_type')
    op.drop_column('alerts', 'source_ip')
    op.drop_column('alerts', 'matched_patterns')
    op.drop_column('alerts', 'confidence_score')
    op.drop_column('alerts', 'status')
    op.drop_column('alerts', 'threat_type')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
