"""Add compliance report table

Revision ID: bfc43d354022
Revises: 8d42e6da7898
Create Date: 2025-07-31 20:12:06.320838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc43d354022'
down_revision: Union[str, None] = '8d42e6da7898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='reportstatus'), nullable=False),
    sa.Column('is_violation', sa.Boolean(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('violation_details', sa.Text(), nullable=True),
    sa.Column('recommended_actions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_reports_alert_id'), 'compliance_reports', ['alert_id'], unique=False)
    op.create_index(op.f('ix_compliance_reports_framework'), 'compliance_reports', ['framework'], unique=False)
    op.create_index(op.f('ix_compliance_reports_id'), 'compliance_reports', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_reports_status'), 'compliance_reports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_reports_status'), table_name='compliance_reports')
    op.drop_index(op.f('ix_compliance_reports_id'), table_name='compliance_reports')
    op.drop_index(op.f('ix_compliance_reports_framework'), table_name='compliance_reports')
    op.drop_index(op.f('ix_compliance_reports_alert_id'), table_name='compliance_reports')
    op.drop_table('compliance_reports')
    # ### end Alembic commands ###
