"""Add foreign key from alerts to logs

Revision ID: ffd5efce1384
Revises: dd244f4648a0
Create Date: 2025-04-09 12:29:15.689427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffd5efce1384'
down_revision: Union[str, None] = 'dd244f4648a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_id', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('log_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['logs.id'], name='alerts_log_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='alerts_pkey')
    )
    op.create_index('ix_alerts_id', 'alerts', ['id'], unique=False)
    # ### end Alembic commands ###
